services:
  - type: web
    name: portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Portfolio.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: django-insecure-g9tkbu#04$2zlmn&#rv_sq7lre8l7%=xk+q3u=d7+44kujrpp=
      - key: ALLOWED_HOSTS
        value: 127.0.0.1,localhost,portfolio-5cmq.onrender.com
